### PR TITLE
Adds X-Tidepool-Trace-Session header to all API requests 

### PR DESCRIPTION
**Pull request by gniezen**
What it says on the tin, and also switches to the `uuid` node package instead of the deprecated `node-uuid` package.

### CODE REVIEW

**Comment by gniezen** [comment]
[[uploader] Add platform X-Tidepool-Trace-Session header to all API requests for improved tracking of errors](https://trello.com/c/aWY4xoU0/197-uploader-add-platform-x-tidepool-trace-session-header-to-all-api-requests-for-improved-tracking-of-errors)

**Comment by gniezen** [comment]
I worked from the spec on the Trello card:

> As a back-end engineer, if an end user reports an error during the upload process, I want to be able to collect up all API requests for the current user "session" (from launch to shutdown of uploader; NOT login to logout of a particular user) from the platform logs so I can debug the problem more quickly and accurately.

If we just want the data from a user session the `X-Tidepool-Session-Token` header should be sufficient, no?

**Comment by gniezen** [comment]
@darinkrauss btw, do you know why the Travis build for platform-client sometimes fails and sometimes passes without changing anything?

**Comment by darinkrauss** [comment]
@gniezen No, though I suspect it is a timing issue between concurrent tests. I haven't dedicated the time to figuring it out. (It has been around for ages.) Just restart the build and it should work.

**Comment by gniezen** [comment]
The changes after this PR was approved should be reviewed. @jh-bate @krystophv do one of you feel comfortable reviewing these, or should we wait until @darinkrauss is back?

**Comment by gniezen** [comment]
[[uploader] Add platform X-Tidepool-Trace-Session header to all API requests for improved tracking of errors](https://trello.com/c/aWY4xoU0/197-uploader-add-platform-x-tidepool-trace-session-header-to-all-api-requests-for-improved-tracking-of-errors)

**Comment by gniezen** [comment]
[[uploader] Add platform X-Tidepool-Trace-Session header to all API requests for improved tracking of errors](https://trello.com/c/aWY4xoU0/197-uploader-add-platform-x-tidepool-trace-session-header-to-all-api-requests-for-improved-tracking-of-errors)

**Pull request merged**
