### PR TITLE
add new custodialSignupConfirm

### PR DESCRIPTION
**Pull request by krystophv**

### CODE REVIEW

**Comment by darinkrauss** [comment]
LGTM :shipit:

**Comment by gniezen** [comment]
@darinkrauss Do you think we can merge and release this together with the `platform-endpoints` changes, or should we rather first do one and then the other?

**Comment by darinkrauss** [comment]
@gniezen I think it is okay to release it together. It looks like it is strictly additive.

**Comment by gniezen** [comment]
Merging.

**Pull request merged**
