### PR TITLE
Returns server time from dataservices API

### PR DESCRIPTION
**Pull request by gniezen**
What it says on the tin.

### CODE REVIEW

**Comment by gniezen** [comment]
[#477 ⁃ [uploader] [timezones] as a user, i want the uploader to warn me of any difference between my device time and computer time or selected timezone in the Uploader and my computer timezone](https://trello.com/c/1eAw2Fpc/175-477-uploader-timezones-as-a-user-i-want-the-uploader-to-warn-me-of-any-difference-between-my-device-time-and-computer-time-or-se)

**Comment by pazaan** [comment]
@gniezen Seems to be failing tests, which is weird. I don't see anything added here that would cause that :(

**Comment by gniezen** [comment]
@pazaan Yeah, failing tests on platform-client is a known issue. Seems to be some kind of race condition, which we just haven't figured out yet.

**Comment by darinkrauss** [comment]
There has been an intermittent failure for a *long* time that we've never gotten around to figuring out. I don't think it is a test failure, but rather a test environment failure.

I *was* trying to kick off another build to get them both green, *but* Travis is having serious problems *and* the branch got merged/deleted. Oh, well, I tried.

**Pull request merged**
