### PR TITLE
Adding data services API

### PR DESCRIPTION
**Pull request by gniezen**
This adds support for the new Data Services API.

### CODE REVIEW

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pkyUK1Uy&#x2F;2-ux-0-dev-5-tst-0-uploader-send-animas-basals-and-suspend-resume-events-with-crud-api"> &lt;ux:0 dev:5 tst:0&gt; [uploader] Send Animas basals and suspend&#x2F;resume events with CRUD API</a>

**Comment by jh-bate** [comment]
@gniezen code looks good and match's the existing stuff. Those tests failures I haven't seen before, it is often one of the message-api tests that fails the first time. I will have a look tomorrow as those might be because of the accounts changes

**Comment by gniezen** [comment]
@jh-bate Any progress on fixing the tests?

**Comment by gniezen** [comment]
@darinkrauss Looks like you and I have duplicated some work. If you're happy that `darinkraus/platform-endpoints` does everything that I did in this PR, please close this one and delete my branch.

**Comment by darinkrauss** [comment]
@gniezen Yes, it looks like the latest Animas work includes all of this functionality. Feel free to close this PR and delete the related branch.

**Pull request closed without merging**
