### PR TITLE
[WEB-2595] critical depandancy updates

### PR DESCRIPTION
**Pull request by clintonium-119**
[WEB-2595] 
Supports https://github.com/tidepool-org/blip/pull/1313

[WEB-2595]: https://tidepool.atlassian.net/browse/WEB-2595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — APPROVED** [review]
LGTM, nice work! 🚢

**Review by krystophv — DISMISSED** [review]
Updates LGTM 💯

**Comment by gniezen** [comment]
@clintonium-119 @krystophv I just realized that Uploader's dependabot update is using `0.54.0-web-2595-critical-depandancy-updates.1` instead of `0.56.0-web-2595-critical-depandancy-updates.1`. When I updated it, it is expecting Node v20.8.0:

```
error tidepool-platform-client@0.56.0-web-2595-critical-depandancy-updates.1: The engine "node" is incompatible with this module. Expected version "20.8.0". Got "18.7.1"
```

 Do we really want to force everyone to use that specific version of Node? 

With Uploader, we usually match the version of Node to that of the Electron version we're using. If i update to the latest version of Electron, that would be Node v20.9.0.

**Comment by krystophv** [comment]
Maybe a more permissive specification is in order, to allow for better compatibility. Something like `>=16`?

**Comment by clintonium-119** [comment]
I'd be fine with allowing a lower version on this repo.  The others (viz, tideline, blip) will need to stay at 20, but this should be fine.  Should we go `>=16`, or `>=18` since that's what @gniezen had been using prior to this?

**Comment by krystophv** [comment]
@clintonium-119 after looking through the current Node.js LTS versions, `>=18` is probably the way to go. 16 support ended inSept 2023.

**Comment by clintonium-119** [comment]
@gniezen Will do shortly

**Review by krystophv — APPROVED** [review]
Updates LGTM!

**Comment by clintonium-119** [comment]
@krystophv Looks like I need re-approval on this.

**Pull request merged**
